business/urls.py
from django.urls import path
from .views import *


app_name = 'business'

urlpatterns = [
    path('',HomePage.as_view(), name='homepage'),
    path('login/', user_login, name='login'),
    path('signup/', user_signup, name='signup'),
    path('logout/', user_logout, name='logout'),
    path('create_plan/', CreateBusinessPlan.as_view(), name='create'),
    
]

business_connector/urls.py
from django.contrib import admin
from django.urls import path,include
from django.contrib.auth.models import Group

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('business.urls',namespace='business')),
]

admin.site.site_header = 'Business Administration'

admin.site.unregister(Group)

business/models.py
from django.db import models
from django.urls import reverse
from django.contrib.auth import get_user_model
from django.core.validators import FileExtensionValidator

User = get_user_model()

class BusinessPlan(models.Model):
    owner = models.ForeignKey(to=User, on_delete=models.CASCADE,null=True)
    business_name = models.CharField(max_length=255,null=True,unique=True,db_index=True)
    email = models.EmailField(null=True)
    description = models.TextField(null=True,max_length=1000)
    plan_doc = models.FileField(upload_to='media/',blank=True,validators=[FileExtensionValidator(allowed_extensions=['pdf','doc','docx'])])
    created_on = models.DateTimeField(auto_now_add=True,null=True)
    modified_on = models.DateTimeField(auto_now=True, null=True)
    business_logo = models.ImageField(null=True, upload_to='media/',blank=False)


    class Meta:
        ordering = ['-created_on']

    def __str__(self):
        return self.business_name
    
    def get_absolute_url(self):
        return reverse("author-detail", kwargs={"pk": self.pk})

business/forms.py
from django import forms 
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from .models import BusinessPlan

class SignupForm(UserCreationForm):
    class Meta:
        model = User 
        fields = ['username','email', 'password1', 'password2']

class LoginForm(forms.Form):
    username = forms.CharField()
    password = forms.CharField(widget=forms.PasswordInput)


class BusinessPlanModelForm(forms.ModelForm):

    class Meta:
        model = BusinessPlan
        fields = ["business_name", "email", "description",'plan_doc','business_logo']

business/views.py
from django.shortcuts import render,redirect
from django.urls import reverse
from django.views.generic import CreateView,UpdateView,ListView,DetailView,DeleteView,View,TemplateView
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.mixins import LoginRequiredMixin
from.models import BusinessPlan
from .forms import UserCreationForm, LoginForm
from django.contrib import messages
from .forms import BusinessPlanModelForm


# signup page
def user_signup(request):
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect(reverse('bussiness:login'))
    else:
        form = UserCreationForm()
    return render(request, 'business/signup.html', {'form': form})

# login page
def user_login(request):
    if request.method == 'POST':
        form = LoginForm(request.POST)
        if form.is_valid():
            username = form.cleaned_data['username']
            password = form.cleaned_data['password']
            user = authenticate(request, username=username, password=password)
            if user:
                login(request, user)    
                return redirect(reverse('business:homepage'))
            messages.warning(request, "Invalid Credentials.")
    else:
        form = LoginForm()
    return render(request, 'business/login.html', {'form': form})

# logout page
def user_logout(request):
    logout(request)
    return redirect(reverse('business:login'))


class HomePage(LoginRequiredMixin,TemplateView):
    template_name ='business/main.html'


class CreateBusinessPlan(LoginRequiredMixin,CreateView):
    template_name ='business/create_business.html'
    model = BusinessPlan
    form_class = BusinessPlanModelForm

    def form_valid(self, form):
        form.instance.owner = self.request.user
        return super().form_valid(form)

class UpdateBusinessPlan(LoginRequiredMixin,UpdateView):
    pass

class BusinessPlanDetailView(LoginRequiredMixin, DetailView):
    context_object_name = "business_plan"
    queryset = BusinessPlan.objects.all()

class DeleteBusinessPlanView(LoginRequiredMixin,DeleteView):
    pass

class ListBusinessPlansView(LoginRequiredMixin,ListView):
    model = BusinessPlan
    context_object_name = "business_plans"
    template_name = 'business/create_business.html'
'''
    queryset = BusinessPlan.objects.order_by("-publication_date")
'''

business/templates/business/create_business.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <!-- Required meta tags-->
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="Colorlib Templates">
    <meta name="author" content="Colorlib">
    <meta name="keywords" content="Colorlib Templates">

    <!-- Title Page-->
    <title>Create Business</title>

    <!-- Font special for pages-->
    <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,600,600i,700,700i,800,800i" rel="stylesheet">

    <!-- Main CSS-->
    <link href="{% static 'css/main.css' %}" rel="stylesheet" media="all">
</head>

<body>
    <div class="page-wrapper bg-dark p-t-100 p-b-50">
        <div class="wrapper wrapper--w900">
            <div class="card card-6">
                <div class="card-heading">
                    <h2 class="title">Create A Business</h2>
                </div>
                <div class="card-body">
                    <form method="POST" action=".">
                        {% csrf_token %}
                        <div class="form-row">
                            <div class="name">Business name</div>
                            <div class="value">
                                <input class="input--style-6" type="text" name="business_name">
                            </div>
                        </div>
                        <div class="form-row">
                            <div class="name">Email address</div>
                            <div class="value">
                                <div class="input-group">
                                    <input class="input--style-6" type="email" name="email" placeholder="example@email.com">
                                </div>
                            </div>
                        </div>
                        <div class="form-row">
                            <div class="name">Business Description</div>
                            <div class="value">
                                <div class="input-group">
                                    <textarea class="textarea--style-6" name="description" placeholder="Message sent to the employer"></textarea>
                                </div>
                            </div>
                        </div>
                        <div class="form-row">
                            <div class="name">Upload Business Plan</div>
                            <div class="value">
                                <div class="input-group js-input-file">
                                    <input class="input-file" type="file" name="plan_doc" id="file">
                                    <label class="label--file" for="file">Choose file</label>
                                    <span class="input-file__info">No file chosen</span>
                                </div>
                                <div class="label--desc">Upload Business Plan or any other relevant file. Max file size 50 MB</div>
                            </div>
                        </div>

                        <div class="form-row">
                            <div class="name">Upload Business Logo</div>
                            <div class="value">
                                <div class="input-group js-input-file">
                                    <input class="input-file" type="file" name="business_logo" id="logo">
                                    <label class="label--file" for="logo">Choose Image file</label>
                                    <span class="input-file__info">No file chosen</span>
                                </div>
                                <div class="label--desc">Upload Business Plan or any other relevant file. Max file size 50 MB</div>
                            </div>
                        </div>
                        <div class="card-footer">
                            <button class="btn btn--radius-2 btn--blue-2" type="submit">Create Business</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>

    <!-- Jquery JS-->
    <script src="{% static 'jquery/jquery.min.js' %}"></script>


    <!-- Main JS-->
    <script src="{% static 'js/global.js' %}"></script>

</body><!-- This templates was made by Colorlib (https://colorlib.com) -->

</html>
<!-- end document-->

business/templates/business/index.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Business</title>
    <!-- font awesome 6 -->
    <link
      rel="stylesheet"
      href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.3.0/css/all.min.css"
      integrity="sha512-SzlrxWUlpfuzQ+pcUCosxcglQRNAq/DZjVsC0lE40xsADsfeQoEypE+enwcOiGjk/bSuGGKHEyjSoQ1zVisanQ=="
      crossorigin="anonymous"
      referrerpolicy="no-referrer"
    />
    <!-- google font -->
    <link rel="preconnect" href="https://fonts.googleapis.com" />
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
    <link href="https://fonts.googleapis.com/css2?family=Montserrat:wght@400;600&display=swap" rel="stylesheet" />
    <!-- custom style -->
    <link rel="stylesheet" href="static/css/style.css" />
  </head>
  <body data-bs-spy="scroll" data-bs-target="#goTop" data-bs-offset="0">
    <!-- topbar -->
    <div id="topbar" class="topbar">
      <div class="container-fluid d-flex justify-content-between">
        <ul class="contact-info d-flex">
          <li>
            <a href="tel:07450225566">
              <i class="fa-solid fa-mobile-screen-button"></i> 
              <span>+237552251615</span>
            </a>
          </li>
          <li>
            <a href="mailto:contact@business.co.uk">
              <i class="fa-regular fa-envelope"></i> 
              <span>contact@business.co.uk</span>
            </a>
          </li>
        </ul>
        <ul class="social-media d-flex">
          <li>
            <a href="#"><i class="fa-brands fa-facebook"></i></a>
          </li>
          <li>
            <a href="#"><i class="fa-brands fa-twitter"></i></a>
          </li>
          <li>
            <a href="#"><i class="fa-brands fa-youtube"></i></a>
          </li>
        </ul>
      </div>
    </div>
    <!-- header -->
    <header id="header">
      <nav class="navbar navbar-expand-lg bg-body-tertiary">
        <div class="container-fluid">
          <a class="navbar-brand" href="#">Business</a>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarScroll" aria-controls="navbarScroll" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon d-flex justify-content-center align-items-center"></span>
          </button>
          <div class="collapse navbar-collapse flex-grow-0" id="navbarScroll">
            <ul class="navbar-nav me-auto my-2 my-lg-0 navbar-nav-scroll" style="--bs-scroll-height: 100px">
              <li class="nav-item">
                <a class="nav-link scrollto active" aria-current="page" href="#hero">Home</a>
              </li>
              <li class="nav-item">
                <a class="nav-link scrollto" href="#about">View Market</a>
              </li>
             
              <li class="nav-item">
                <a class="nav-link scrollto" href="#teams">Create Business Plan</a>
              </li>
              {% if not request.user.is_authenticated %}
              <li class="nav-item">
                <a class="nav-link scrollto" href="{% url 'business:signup' %}">Sign Up</a>
              </li>
              <li class="nav-item">
                <a class="nav-link scrollto" href="{% url 'business:login' %}">Login</a>
              </li>
              {% else %}
              <li class="nav-item">
                <a class="nav-link scrollto" href="{% url 'business:logout' %}">Logout</a>
              </li>
              {% endif %}
            </ul>
          </div>
        </div>
      </nav>
    </header>
    <!-- main -->
    <main>
      <!-- hero -->
      <div id="hero" class="carousel slide">
        <div class="carousel-indicators">
          <button type="button" data-bs-target="#hero" data-bs-slide-to="0" class="active" aria-current="true" aria-label="Slide 1">Invest</button>
          <button type="button" data-bs-target="#hero" data-bs-slide-to="1" aria-label="Slide 2">Create </button>
          <button type="button" data-bs-target="#hero" data-bs-slide-to="2" aria-label="Slide 3"></button>
        </div>
        <div class="carousel-inner">
          <div class="carousel-item active">
            <img src="static/images/img-banner1.jpg" class="d-block w-100" alt="banner 1" />
            <div class="carousel-caption d-none d-lg-block">
              <h5>Revolutionize Your Business</h5>
              <p>
                In today's rapidly changing business landscape, it's crucial to stay ahead of the curve. Revolutionize Your Business explores the power of innovation and adaptability, providing
                practical strategies for transforming your company and driving growth.
              </p>
            </div>
          </div>
          <div class="carousel-item">
            <img src="static/images/img-banner2.jpg" class="d-block w-100" alt="banner 2" />
            <div class="carousel-caption d-none d-lg-block">
              <h5>Unlock Your Business Potential</h5>
              <p>
                Unlock Your Business Potential provides actionable insights for achieving growth and success. Learn how to optimize operations, streamline processes, and drive innovation to take your
                business to the next level.
              </p>
            </div>
          </div>
          <div class="carousel-item">
            <img src="static/images/img-banner3.jpg" class="d-block w-100" alt="banner 3" />
            <div class="carousel-caption d-none d-lg-block">
              <h5>Mastering the Art of Entrepreneurship</h5>
              <p>
                Mastering the Art of Entrepreneurship is a comprehensive guide to building a successful business. From ideation to launch and beyond, this guide covers the essential skills, tools, and
                strategies for aspiring entrepreneurs.
              </p>
            </div>
          </div>
        </div>
      </div>
      <!-- about -->
      <!-- services -->
     <!-- faq -->
      <!-- contact -->
      
    <!-- footer -->
    <footer id="footer">
      <div class="container-fluid">
        <div class="row py-md-5 py-3 gy-4 border-bottom border-white">
          <div class="col-md-3 col-sm-6">
            <h2>Business</h2>
            <p>Buea, South West, Cameroon</p>
            <ul>
              <li><strong>Phone:</strong>07450225566</li>
              <li><strong>Email:</strong>contact@business.co.uk</li>
            </ul>
          </div>
          <div class="col-md-3 col-sm-6">
            <h5>Useful links</h5>
            <ul class="list-group">
              <li class="list-group-item"><a href="#">Terms &amp; condition</a></li>
              <li class="list-group-item"><a href="#">Privacy policy</a></li>
            </ul>
          </div>
          <div class="col-md-3 col-sm-6">
            <h5>Our services</h5>
            <ul class="list-group">
              <li class="list-group-item"><a href="#">Business Plan Writing</a></li>
              <li class="list-group-item"><a href="#">CV creation</a></li>
              <li class="list-group-item"><a href="#">Web hosting</a></li>
              <li class="list-group-item"><a href="#">Email marketing</a></li>
            </ul>
          </div>
          <div class="col-md-3 col-sm-6">
            <h5>Our social networks</h5>
            <p>Stay connected, stay informed, stay inspired</p>
            <ul class="d-flex social">
              <li>
                <a href="#"><i class="fa-brands fa-square-facebook"></i></a>
              </li>
              <li>
                <a href="#"><i class="fa-brands fa-instagram"></i></a>
              </li>
              <li>
                <a href="#"><i class="fa-brands fa-youtube"></i></a>
              </li>
              <li>
                <a href="#"><i class="fa-brands fa-linkedin"></i></a>
              </li>
            </ul>
          </div>
        </div>
        <div class="row py-4 text-center">
          <p class="m-0">Copyright &copy; 2023. All rights reserved.</p>
        </div>
      </div>
    </footer>
    <!-- to top -->
    <div id="goTop">
      <a href="#topbar" id="goTopBtn"><i class="fa-solid fa-chevron-up"></i></a>
    </div>
    <!-- bootstrap -->
    <script
      src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js"
      integrity="sha384-w76AqPfDkMBDXo30jS1Sgez6pr3x5MlQ1ZAGC+nuZB+EYdgRZgiwxhTBTkF7CXvN"
      crossorigin="anonymous"
    ></script>
    <script>
      let goTopBtn = document.getElementById("goTopBtn");
      window.onscroll = function () {
        scrollFunction();
      };
      function scrollFunction() {
        if (document.body.scrollTop > 20 || document.documentElement.scrollTop > 20) {
          goTopBtn.style.display = "flex";
        } else {
          goTopBtn.style.display = "none";
        }
      }
    </script>
  </body>
</html>

business/templates/business/login.html
{% load static %}
{%load crispy_forms_tags %} 
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Login as investor</title>

    <!-- Font Icon -->
    <link rel="stylesheet" href="{% static 'fonts/material-icon/css/material-design-iconic-font.min.css' %}">

    <!-- Main css -->
    <link rel="stylesheet" href="{% static 'css/styles.css' %}">
</head>
<body>
      <!-- Sing in  Form -->
      <section class="sign-in">
        <div class="container">
            <div class="signin-content">
                <div class="signin-image">
                    <figure><img src="{% static 'images/signin-image.jpg' %}" alt="sing up image"></figure>
                    <a href="{% url 'business:signup' %}" class="signup-image-link">Sign Up</a>
                </div>

                <div class="signin-form">
                    <h2 class="form-title">Login</h2>
                    {% if messages %}
                    <ul class="messages">
                        {% for message in messages %}
                        <li  {% if message.tags %} class="{{ message.tags }}"{% endif %}><h1>{{ message }}</h1></li>
                        {% endfor %}
                    </ul>
                    {% endif %}
                    <form method="POST" class="register-form" id="login-form" action=".">
                        {% csrf_token %}
                     
                        {% comment %}
                        {{ form|crispy }}
                        <button type="submit">Login</button>
                        {% endcomment %}
                

                        <div class="form-group">
                            <label for="your_name"><i class="zmdi zmdi-account material-icons-name"></i></label>
                            <input type="text" name="username" id="username" placeholder="Your Name or password"/>
                        </div>
                        <div class="form-group">
                            <label for="your_pass"><i class="zmdi zmdi-lock"></i></label>
                            <input type="password" name="password" id="password" placeholder="Password"/>
                        </div>
                        <div class="form-group">
                            <input type="checkbox" name="remember-me" id="remember-me" class="agree-term" />
                            <label for="remember-me" class="label-agree-term"><span><span></span></span>Remember me</label>
                        </div>
                        <div class="form-group form-button">
                            <input type="submit" name="signin" id="signin" class="form-submit" value="Log in"/>
                        </div>
                    </form>
                    <div class="social-login">
                        <span class="social-label">Or login with</span>
                        <ul class="socials">
                            <li><a href="#"><i class="display-flex-center zmdi zmdi-facebook"></i></a></li>
                            <li><a href="#"><i class="display-flex-center zmdi zmdi-twitter"></i></a></li>
                            <li><a href="#"><i class="display-flex-center zmdi zmdi-google"></i></a></li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </section>

</div>

<!-- JS -->
<script src="{% static 'vendor/jquery/jquery.min.js' %}"></script>
<script src="{% static 'js/main.js' %}"></script>
</body>
</html>

business/templates/business/signup.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Sign Up  as an investor</title>

    <!-- Font Icon -->
    <link rel="stylesheet" href="{% static 'fonts/material-icon/css/material-design-iconic-font.min.css' %}">

    <!-- Main css -->
    <link rel="stylesheet" href="{% static 'css/styles.css' %}">
</head>
<body>

    <div class="main">

        <!-- Sign up form -->
        <section class="signup">
            <div class="container">
                <div class="signup-content">
                    <div class="signup-form">
                        <h2 class="form-title">Sign up</h2>
                        <form method="POST" class="register-form" id="register-form" action=".">
                            {% csrf_token %}
                            <div class="form-group">
                                <label for="name"><i class="zmdi zmdi-account material-icons-name"></i></label>
                                <input type="text" name="username" id="username" placeholder="username"/>
                            </div>
                            <div class="form-group">
                                <label for="email"><i class="zmdi zmdi-email"></i></label>
                                <input type="email" name="email" id="email" placeholder="Your Email"/>
                            </div>
                            <div class="form-group">
                                <label for="pass"><i class="zmdi zmdi-lock"></i></label>
                                <input type="password" name="password1" id="password1" placeholder="Password"/>
                            </div>
                            <div class="form-group">
                                <label for="re-pass"><i class="zmdi zmdi-lock-outline"></i></label>
                                <input type="password" name="password2" id="password2" placeholder="Repeat your password"/>
                            </div>
                            <div class="form-group">
                                <input type="checkbox" name="agree-term" id="agree-term" class="agree-term" />
                                <label for="agree-term" class="label-agree-term"><span><span></span></span>I agree all statements in  <a href="#" class="term-service">Terms of service</a></label>
                            </div>
                            <div class="form-group form-button">
                                <input type="submit" name="signup" id="signup" class="form-submit" value="Register"/>
                            </div>
                        </form>
                    </div>
                    <div class="signup-image">
                        <figure><img src="{% static 'images/signup-image.jpg' %}" alt="sing up image"></figure>
                        <a href="{% url 'business:login' %}" class="signup-image-link">I am already member</a>
                    </div>
                </div>
            </div>
        </section>

    <!-- JS -->
<script src="{% static 'jquery/jquery.min.js' %}"></script>
    <script src="{% static 'js/main.js' %}"></script>
</body>
</html>